### ISSUE TITLE
NAM nest vs RRFS_A precip comparisons not loading

### ISSUE THREAD

**Issue by JacobCarley-NOAA** [BenjaminBlake-NOAA/RRFS_plot_python#12]
Upon looking at precip forecasts this morning for Idalia I noticed that the QPF comparisons between the NAM nest and RRFS_A fail to load.

**Comment by BenjaminBlake-NOAA** [comment]
@JacobCarley-NOAA  Thank you for opening an issue for this.  I am implementing a few changes to the graphics workflow today, which should resolve this issue in addition to issues 7, 9, and 11.

**Comment by BenjaminBlake-NOAA** [comment]
The issue with the NAM nest vs RRFS_A QPF difference plots has been fixed and they should appear going forward.
